### ISSUE TITLE
what's the use case scenario of this repository?

### ISSUE THREAD

**Issue by kingzleshe** [cenk1cenk2/docker-softether-vpnsrv#14]
I'm just curious to ask

**Comment by cenk1cenk2** [comment]
Runs the softether vpn server inside a container, which I convenient for myself because everything is dockerized for me.  Can also run multiple isolated servers on the same server, if I wish to.

Also softether vpn server does not come with a DHCP server and uses its internal secure nat feature which is not performant enough for me.
