### ISSUE TITLE
Experimental build

### ISSUE THREAD

**Issue by dormancygrace** [cenk1cenk2/docker-softether-vpnsrv#31]
Hi. Me, again. Can you make experimental build, based on Ubuntu/OracleLinux instead of Alpine?

**Comment by dormancygrace** [comment]
https://github.com/cenk1cenk2/docker-softether-vpnsrv/pull/33

**Comment by cenk1cenk2** [comment]
hey @dormancygrace 
i can merge this in tomorrow evening but wouldnt it be better with debian slim due to size, is there any particular reason for ubuntu.

maybe i should refactor the main dockerfiles to multisage ones too, seeing yours made me realize how lazy i have been throughout years

**Comment by dormancygrace** [comment]
I'll try with debian, but final image on Ubuntu just near 130 MB (arm64).

And I think I can further optimize Dockerfile. I want to try make static build

**Comment by dormancygrace** [comment]
If you make multistage build, then you can build go part in container too. My Dockerfile is just yours, adopted to Ubuntu. We can skip make install option for sure

**Comment by cenk1cenk2** [comment]
Ubuntu arm64 version fails very interestingly while doing the library patch since there is a problem on the upstream side with arm detection, I have no idea why Alpine passes and this fails where they both use sh at the build.
https://gitlab.kilic.dev/docker/softether-vpnsrv/-/jobs/46525#L3172

I am mostly braindead for today, if you want to have a go at it the idea is you can do that on the docker-compose file by changing the TARGETARCH to arm64 and wait for the echo to happen normally.

**Comment by dormancygrace** [comment]
Strange, I've built it without any problems https://hub.docker.com/r/dormancygrace/softether

**Comment by dormancygrace** [comment]
Where is git clone $repository? )

**Comment by dormancygrace** [comment]
And why there is apt-get in dockerfile?

**Comment by dormancygrace** [comment]
I'll try tomorrow further optimize Dockerfiles. We can skip "make install" step. For submodules init and update better to use git submodule update --init --recursive

**Comment by cenk1cenk2** [comment]
> Where is git clone $repository? )

I wantes to give a try to experimental synatx where it would automatically cache the sha hopefully so it would rebuild on repository change.

But didnt get the chance to test it since it could not push images yet.

**Comment by cenk1cenk2** [comment]
This took some effort and had to build all my builder images as ARM too and I started to natively build the arm64 images on Oracle Cloud instead of emulating for an hour to produce as per your guidance. Still, it is now available for both Alpine and ubuntu.

https://hub.docker.com/r/cenk1cenk2/softether-vpnsrv/tags

**Comment by dormancygrace** [comment]
🍻 mazel tov! 

P.S.: what OS you use on Oracle instance? If you don't mind, please, contact me via email "nickname"@gmail.com
